### ISSUE TITLE
Problem，exchange

### ISSUE THREAD

**Issue by wangsen0518** [icon-project/t-bears#12]
Hi,

I an a developer on the exchange and our exchange wants to develop a wallet based on the iocn public chain.

I learned from the telegram volunteers that the icon official does not allow to synchronize the full node locally only allowing access to the full node data via the official url.As far as I know some large exchanges such as binance.okex... has completed the icon's main network switch and has supported deposit/withdraw icon main chain token.Do you know how they can support the icon main network token deposit/witdraw without being able to synchronize the icon full node locally?Are they using official urls?Or what else is there for the exchanges?

In the worst case, we can only access the icon public chain data by using the official url. Can you provide multiple statble urls?

I hope you reply as soon as possible.You can reply to my email attkernel@gmail.com

Thanks,

Alger

**Comment by eunsoo-icon** [comment]
HI, wangsen0518 

Our staff will contact you.
