### ISSUE TITLE
Please fix "Setup on MacOS" steps on https://icondev.io/gettingStart01.do

### ISSUE THREAD

**Issue by rappad** [icon-project/t-bears#4]
Setup on MacOS topic on https://icondev.io/gettingStart01.do says "pip install t-bears" instead of "pip install tbears". This will definitely confuse developers who recently jumps into ICON dapp development.

**Comment by sojinkim-icon** [comment]
Thanks for your reporting. Will fix.

**Comment by Spl3en** [comment]
> Thanks for your reporting. Will fix.

I noticed there are some typos on the icondev website as well (for instance on gettingStart01.do, "development **environrment**" should be "development **environmnent**".

What is the correct procedure for fixing these typos?
Thank you.

**Comment by sojinkim-icon** [comment]
@Spl3en For now, the dev site contents do not automatically sync up with the GitHub docs. They are two different copies of a file, and in the long run they will diverge. So, the best way would be, for any fix or improvement suggestion for the dev site, please directly report to them (https://www.icondev.io/introduction01.do#contact_us).  For GitHub docs, we will discuss formal contribution procedure and will update you.
