### ISSUE TITLE
update installation steps. error while installing libleveldb1

### ISSUE THREAD

**Issue by FidelVe** [icon-project/t-bears#62]
When trying to install I get the following message when running `sudo apt-get install libleveldb1 libleveldb-dev`

```
Package libleveldb1 is not available, but is referred to by another package.    
This may mean that the package is missing, has been obsoleted, or               
is only available from another source                                           
However the following packages replace it:                                      
  libleveldb1v5                                                                 
                                                                                
E: Package 'libleveldb1' has no installation candidate
```

on the latest versions of Ubuntu the `libleveldb1` package is now under the `libleveldb1v5` package
https://packages.ubuntu.com/search?keywords=libleveldb1

**Comment by eunsoo-icon** [comment]
Thanks for reporting. I will check this and give you a result.

**Comment by eunsoo-icon** [comment]
Sorry for late response.

I ran commands in [Setup on Linux](https://github.com/icon-project/t-bears#setup-on-linux) and got a same error message on "Ubuntu 18.04.1 LTS"

I will modify README.md 
- remove `libleveldb1` installsation because we will install `libleveldb-dev`....
- add rabbitmq-server start command

**Comment by FidelVe** [comment]
So `libleveldb1v5` is not necessary?

**Comment by eunsoo-icon** [comment]
Yes `libleveldb-dev` is enough

**Comment by FidelVe** [comment]
Great thanks you can close the issue if you like :+1:
