### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'revision' 

### ISSUE THREAD

**Issue by prajwolrg** [icon-project/t-bears#72]
I am learning how to write unit tests in SCORE. For that I have implemented a simple Election SCORE. This includes the following method:

@external(readonly=True)
def get_candidates_number(self) -> int:
  return len(self._registered_candidates)  
#self._registered_candidates = ArrayDB(Election._REGISTERED_CANDIDATES, db, Address)

In the unit test :
def test_get_candidates_number(self):
  self.assertEqual(0, self.score.get_candidates_number())

I am getting the following error:
======================================================================
ERROR: test_get_candidates_number (election.tests.test_unit_election.TestElection)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/prajwolrg/SCORE/election/tests/test_unit_election.py", line 30, in test_get_candidates_number
    self.assertEqual(0, self.score.get_candidates_number())
  File "/home/prajwolrg/.local/lib/python3.8/site-packages/tbears/libs/scoretest/patch/score_patcher.py", line 108, in patched
    result = method(*args, **kwargs)
  File "/home/prajwolrg/.local/lib/python3.8/site-packages/iconservice/iconscore/icon_score_base.py", line 264, in wrapper
    res = func(calling_obj, *args, **kwargs)
  File "/home/prajwolrg/SCORE/election/election.py", line 77, in get_candidates_number
    return len(self._registered_candidates)
  File "/home/prajwolrg/.local/lib/python3.8/site-packages/iconservice/iconscore/icon_container_db.py", line 297, in __len
    return self.__get_size()
  File "/home/prajwolrg/.local/lib/python3.8/site-packages/iconservice/iconscore/icon_container_db.py", line 276, in __get_size
    if self.__is_defective_revision():
  File "/home/prajwolrg/.local/lib/python3.8/site-packages/iconservice/iconscore/icon_container_db.py", line 326, in __is_defective_revision
    revision = context.revision
AttributeError: 'NoneType' object has no attribute 'revision'

----------------------------------------------------------------------
Ran 6 tests in 0.214s

**Comment by inwonkim** [comment]
Hi, thank you for report.
Since the SCORE unittest framework is a package in t-bears, I have transferred this issue to the t-bears issue.

**Comment by mr-rooftop** [comment]
As this got already merged on June 23, which tbears version has to be used to enjoy the fix?

**Comment by inwonkim** [comment]
We release new version(1.7.0) on pypi.
reinstall t-bears and enjoy the fix.

**Comment by eunsoo-icon** [comment]
Sorry to confuse everyone.

T-Bears 1.7.0 has a bug in the `sync_mainnet` command.

We fix it and release T-Bears 1.7.1.

Please reinstall T-Bears.

**Comment by mr-rooftop** [comment]
There seems to be an issue with the versions on pypi.

When I try to install tbears I get:
```
Collecting tbears
  Downloading https://files.pythonhosted.org/packages/78/8c/d4c99058699eb3e7be5e0162d4da6bc8b0df05ad71edb17c1822e2e15ef2/tbears-1.7.1-py3-none-any.whl (381kB)
.
.
.
Collecting iconservice~=1.7.3 (from tbears)

  Could not find a version that satisfies the requirement iconservice~=1.7.3 (from tbears) (from versions: 1.0.3, 1.0.5, 1.0.6, 1.0.6.2, 1.1.1, 1.1.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4.1, 1.4.2, 1.4.3, 1.5.15, 1.5.18, 1.5.20, 1.6.0, 1.6.1)
No matching distribution found for iconservice~=1.7.3 (from tbears)
```

Then when I try to install iconservice `1.7.1`, `1.7.2` or `1.7.3`, I always get:
```
$ pip install iconservice==1.7.3 
Collecting iconservice==1.7.3
  Could not find a version that satisfies the requirement iconservice==1.7.3 (from versions: 1.0.3, 1.0.5, 1.0.6, 1.0.6.2, 1.1.1, 1.1.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4.1, 1.4.2, 1.4.3, 1.5.15, 1.5.18, 1.5.20, 1.6.0, 1.6.1)
No matching distribution found for iconservice==1.7.3
```

I'm using python `3.6.9`

**Comment by eunsoo-icon** [comment]
iconservice-1.7.3 requires  `Python>=3.7, <3.8`. Please upgrade python to 3.7

We will modify T-Bears python requirements too.
