### ISSUE TITLE
concurrent.futures._base.CancelledError

### ISSUE THREAD

**Issue by sashapopov94** [icon-project/t-bears#88]
Hello. I installed the latest version of T-bears ( 1.8.0) but I am having a problem deploying a hello-world contract  on the local emulated environment. I get this error : 

 concurrent.futures._base.CancelledError 

and I also get the same error when I run the command tbears start. Do you have any suggestions how to fix this issue?

**Comment by eunsoo-icon** [comment]
Can you share the error message?

**Comment by sashapopov94** [comment]
Sure. This happens when I activate the virtual environment and execute `tbears start`. I upgraded RabbitMQ-server to version 3.8.19 and icon-service to version 1.8.4.

<pre>ERROR:root:
Traceback (most recent call last):
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/jsonrpcserver/dispatcher.py&quot;, line 123, in handle_exceptions
    yield handler
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/jsonrpcserver/async_dispatcher.py&quot;, line 40, in safe_call
    lookup(methods, request.method), *request.args, **request.kwargs
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/jsonrpcserver/async_dispatcher.py&quot;, line 34, in call
    return await validate_args(method, *args, **kwargs)(*args, **kwargs)
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/iconrpcserver/dispatcher/v3/icx.py&quot;, line 41, in icx_call
    response = await score_stub.async_task().query(request)
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/earlgrey/message_queue_stub.py&quot;, line 129, in _call_async_rpc
    result = await self._rpc_client_async.call(func_name, kwargs=params.arguments, priority=priority)
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/earlgrey/patterns/rpc/client_async.py&quot;, line 135, in call
    return (yield from future)
concurrent.futures._base.CancelledError
</pre>

**Comment by eunsoo-icon** [comment]
T-Bears requires iconservice >= 1.8.9.

Please update iconservice and share the result to me

**Comment by sashapopov94** [comment]
Sorry, I made a mistake ... My iconservice is already at version **1.8.10.** When I run iconservice start I get 

<pre>  File &quot;/usr/lib/python3.7/runpy.py&quot;, line 193, in _run_module_as_main
    &quot;__main__&quot;, mod_spec)
  File &quot;/usr/lib/python3.7/runpy.py&quot;, line 85, in _run_code
    exec(code, run_globals)
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/iconservice/icon_service.py&quot;, line 233, in &lt;module&gt;
    main()
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/iconservice/icon_service.py&quot;, line 183, in main
    icon_service.serve(config=conf)
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/iconservice/icon_service.py&quot;, line 83, in serve
    self._inner_service = IconScoreInnerService(amqp_target, self._icon_score_queue_name, conf=config)
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/earlgrey/message_queue_service.py&quot;, line 39, in __init__
    self._task = self.__class__.TaskType(**task_kwargs)
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/iconservice/icon_inner_service.py&quot;, line 62, in __init__
    self._open()
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/iconservice/icon_inner_service.py&quot;, line 74, in _open
    self._icon_service_engine.open(self._conf)
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/iconservice/icon_service_engine.py&quot;, line 227, in open
    conf[ConfigKey.ICON_RC_MONITOR])
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/iconservice/icon_service_engine.py&quot;, line 307, in _open_component_context
    icon_rc_monitor)
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/iconservice/iiss/engine.py&quot;, line 125, in open
    self._init_reward_calc_proxy(log_dir, data_path, socket_path, ipc_timeout, icon_rc_path, icon_rc_monitor)
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/iconservice/iiss/engine.py&quot;, line 240, in _init_reward_calc_proxy
    icon_rc_monitor=icon_rc_monitor
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py&quot;, line 111, in start
    icon_rc_monitor=icon_rc_monitor)
  File &quot;/home/aleksandar/Projects/AZSoft/Tbears/venv/lib/python3.7/site-packages/iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py&quot;, line 585, in start_reward_calc
    self._reward_calc = Popen(args)
  File &quot;/usr/lib/python3.7/subprocess.py&quot;, line 800, in __init__
    restore_signals, start_new_session)
  File &quot;/usr/lib/python3.7/subprocess.py&quot;, line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: &apos;icon_rc&apos;: &apos;icon_rc&apos;
</pre>

**Comment by eunsoo-icon** [comment]
You can install icon_rc with [ICON reward calculator](https://github.com/icon-project/rewardcalculator). Needed GO

I will update README.md with this content if necessary

**Comment by sashapopov94** [comment]
> You can install icon_rc with [ICON reward calculator](https://github.com/icon-project/rewardcalculator). (Needed GO)
> 
> I will update README.md with this content if necessary

Thank you very much. It did the trick.
